### PR TITLE
Multi language and framework support

### PR DESCRIPTION
**Pull request by domyen**
This PR encapsulates the work necessary to support multiple languages and frameworks. 

**Todo**
- [x] Figure out how to structure app to present different view layers #1 and languages #12
- [x] Add Tooltip component to switch between view layers and languages in `Header.js`

### CODE REVIEW

**Comment by tmeasday** [comment]
@domyen how are we going to deal with the intersection between languages and frameworks? e.g. we aren't going to have Spanish text for the Vue code. I don't know if the translators are going to be keen to do multiple versions. 

Perhaps the chooser should be more lang+framework at the same time:

 - React / English
 - Vue / English
 - React / Spanish
 - Add another?

**Comment by tmeasday** [comment]
Additionally, what do we want the URLs to look like? 

Do we want to special case the React/English URLs (so say learnstorybook.com/get-started goes to React/English) or fully qualify everything (so it'd be learnstorybook.com/react/english/get-started), or both?

**Comment by tmeasday** [comment]
Also we have a few strings littered through the UI, should we translate them too?

 - 'Tweet "I'm learning Storybook! It’s a great dev tool for UI components."'
 - 'Next chapter'
 - 'Edit on GitHub
 - 'Keep your code in sync with this chapter. View {commit} on GitHub'
 - 'Table of Contents'

**Comment by domyen** [comment]
**URL strawman**
- We fully qualify all urls (but default to React + English with the appropriate redirects).
- URL syntax is `learnstorybook.com/react/en/get-started` (use language [shorthand](https://github.com/hichroma/learnstorybook.com/issues/3#issuecomment-387155701) for languages)
- File system should mirror the URL. So we need to add `/react` and `/vue` under `/content`.

**Localization of UI**
Punt for now. Let's just work on supporting the content.

**Picker UI**
Your suggestion makes sense. Will update the picker to be formatted like this:
 
image

**Comment by tmeasday** [comment]
@domyen take a look at this now. I think it's pretty close to done (for React en/es).

Let me know what I missed. It's not the cleanest ever but it works. I'd like to do a pass over it and get linting working and clean up a bit once we are satisfied with the functionality.

**Comment by domyen** [comment]
@tmeasday can you hook the React tooltip link up so that it changes depending on which framework you select?

image

**Comment by domyen** [comment]
@icarlossz do you mean the twitter message "I'm learning Storybook..."? 

And great catch re:github "edit on GitHub" link!

**Comment by tmeasday** [comment]
Are we planning on translating the internal language (e.g. the tweet?).

Otherwise I think this is good to go, let's merge and we can make any fixes on `master`

**Comment by tmeasday** [comment]
Going to merge this! Hope I didn't mess up the spanish @icarlossz

**Pull request merged**
